name: LoboBrowser Legal
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "with_toc_data", "autolink"]
pygments:  true
highlighter: pygments
permalink: pretty
baseurl:   //legal.lobobrowser.org
docsurl: //docs.lobobrowser.org
mainsiteurl: //lobobrowser.org
cobrasite: //cobra.lobobrowser.org
communitysite: //forums.lobobrowser.org
extendsite: //extend.lobobrowser.org
blogsite: //blog.lobobrowser.org
